### ISSUE TITLE
Reckless and irresponsible usage instructions endanger users

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/amazon-inspector-image-scanner-plugin#11]
### Describe your use-case which is not covered by existing documentation.

Per https://github.com/jenkinsci/amazon-inspector-image-scanner-plugin/blob/main/README.md

> Add CSS support in Jenkins script console to allow the HTML report link to open
> Go to Dashboard > Manage Jenkins > Nodes > Built-In Node and select the Gear icon and navigate to script console
> Add in script System.setProperty("hudson.model.DirectoryBrowserSupport.CSP", "") and click Run

These instructions are dangerous, as anyone following them is newly massively vulnerable to cross-site scripting attacks by following them. Just link to https://www.jenkins.io/doc/book/security/user-content/ instead and let admins decide how to handle this.

**Comment by waltwilo** [comment]
Thanks for pointing this out, we're addressing this in the following PR: https://github.com/jenkinsci/amazon-inspector-image-scanner-plugin/pull/14
