### ISSUE TITLE
Add an example how to run as part of a Jenkins declarative pipeline 

### ISSUE THREAD

**Issue by moshen-maverick** [jenkinsci/amazon-inspector-image-scanner-plugin#12]
### Describe your use-case which is not covered by existing documentation.

We use Jenkins declarative pipelines to run all our builds. A few good examples how to use this plugin as part of a declarative pipeline will be excellent. 
Using the example provided by the plugin pipeline syntax (step Amazon Inspector(archivePath: '', awsRegion: 'null', countCritical: 0, countHigh: 0, countLow: 10, countMedium: 5, credentialId: 'null', iamRole: '', sbomgenPath: '')) is not working and its not clear why

**Comment by naveshal** [comment]
Thank you for feedback. Here is declarative pipeline example.

pipeline {
    agent any
    stages {
        stage('amazon-inspector-image-scanner') {
            steps {
                script {
                step([
                $class: 'com.amazon.inspector.jenkins.amazoninspectorbuildstep.AmazonInspectorBuilder',
                sbomgenPath: '<<Add Path>>',
                archivePath: '<<Add Path>>',
                awsRegion: 'us-east-1',
                iamRole: '<<Add Role>>',
                credentialId: '<<Add ID>>',
                isThresholdEnabled: false/true,
                countCritical: 0, 
                countHigh: 0, 
                countLow: 10, 
                countMedium: 5,
               ])
            }
         }
       }
    }
}

**Comment by cjbaco** [comment]
AWS [documentation](https://docs.aws.amazon.com/inspector/latest/user/cicd-jenkins.html) also updated with an example.
